name: Docker image stage CI

on:
  push:
    # branches-ignore:
    #   - master
    paths-ignore:
      - README.md
      - .gitignore
      - .gitattributes
      - .editorconfig
      - research
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
      - .gitattributes
      - .editorconfig
      - research

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          docker build --force-rm -t ghcr.io/xausssr/vasilisc.budget .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}}" ghcr.io/${{ github.repository_owner }}/vasilisc.budget* | while read IMAGE; do
            IMAGE_ID=$(echo $IMAGE | awk -F ":" '{print $1}')
            docker tag $IMAGE $IMAGE_ID:$GITHUB_SHA
            docker push $IMAGE_ID
          done
